name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git config --global --add safe.directory '*'
          git clone --depth 1 "https://git.hoelee.com/hoelee/hoelee-blog.git" .
          ls -la

      - name: Node version
        run: node --version && npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: List output
        run: ls -la dist/
